# Generated by Django 3.1.7 on 2021-05-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='readConf',
            field=models.BooleanField(default=False),
        ),
    ]
