# Generated by Django 3.1.7 on 2021-04-11 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20210411_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='encharge',
            new_name='inCharge',
        ),
        migrations.AddField(
            model_name='project',
            name='Description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ProjectName',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='workDone',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
