# Generated by Django 3.1.7 on 2021-04-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20210411_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='language',
            field=models.CharField(choices=[('JA', 'Java'), ('CC', 'C'), ('C+', 'C++'), ('PY', 'Python'), ('C#', 'C#'), ('RE', 'React'), ('HT', 'HTML'), ('PH', 'php'), ('DB', 'DB')], default='JA', max_length=2),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('JU', 'Junior'), ('SE', 'Senior'), ('EX', 'expert')], default='JU', max_length=2),
        ),
    ]
