# Generated by Django 3.1.7 on 2021-04-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20210411_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
