# Generated by Django 3.1.7 on 2021-04-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_auto_20210411_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='allTasks',
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SprintName', models.CharField(max_length=300)),
                ('Descripion', models.CharField(max_length=300)),
                ('StartTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('allTasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.task')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='allSprint',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='work.sprint'),
            preserve_default=False,
        ),
    ]
