# Generated by Django 3.1.7 on 2021-04-21 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='workDone',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
