# Generated by Django 3.1.7 on 2021-05-20 18:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_conclusions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='allSprint',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='allTasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subTasks',
        ),
        migrations.AddField(
            model_name='sprint',
            name='projectnum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.project'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='subTasks',
            field=models.ForeignKey( null=True,on_delete=django.db.models.deletion.CASCADE, to='work.task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='SpirntNum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.sprint'),
        ),
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='workDone',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),

    ]
