# Generated by Django 3.1.7 on 2021-05-21 11:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_auto_20210521_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Budget',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtask',
            name='workDone',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='workDone',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),

    ]
