# Generated by Django 3.1.7 on 2021-05-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_auto_20210521_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='MoneySpends',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='currentBudgeSchedule',
            field=models.FloatField(default=0, null=True),
        ),

    ]
