# Generated by Django 3.1.7 on 2021-05-21 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_auto_20210521_1455'),
    ]

    operations = [

    ]
