# Generated by Django 3.1.7 on 2021-05-22 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0019_auto_20210522_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Budget',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='MoneySpends',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='currentBudgeSchedule',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='cost',
            field=models.FloatField(default=0),
        ),

    ]
