# Generated by Django 3.1.7 on 2021-05-22 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_auto_20210522_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='subTasks',
            new_name='TaskID',
        ),
        migrations.RemoveField(
            model_name='task',
            name='SpirntNum',
        ),
        migrations.AlterField(
            model_name='project',
            name='startTime',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Sprint_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpirntId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.sprint')),
                ('TaskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.task')),
            ],
        ),

    ]
