# Generated by Django 3.1.7 on 2021-05-22 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0021_auto_20210522_2028'),
    ]

    operations = [

    ]
