# Generated by Django 3.1.7 on 2021-05-22 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0022_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),

    ]
