# Generated by Django 3.1.7 on 2021-05-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_auto_20210522_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='work.subtask')),
            ],
        ),
    ]
