# Generated by Django 3.1.7 on 2021-05-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0024_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lastUpdate',
            field=models.DateField(),
        ),
    ]
