# Generated by Django 3.1.7 on 2021-05-30 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0026_auto_20210529_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='auth.user'),
            preserve_default=False,
        ),
    ]
