# Generated by Django 3.1.7 on 2021-05-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0027_project_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.project')),
                ('SprintId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.sprint')),
            ],
        ),
    ]
