# Generated by Django 3.1.7 on 2021-05-31 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0028_sprint_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='projectnum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='work.project'),
            preserve_default=False,
        ),
    ]
