# Generated by Django 3.1.7 on 2021-06-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0029_task_projectnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='inSprint',
            field=models.BooleanField(default=False),
        ),
    ]
