# Generated by Django 3.1.7 on 2021-06-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0030_task_insprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
