# Generated by Django 3.1.7 on 2021-05-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicem',
            old_name='choiceM_text',
            new_name='choice_text',
        ),
        migrations.AlterField(
            model_name='choicem',
            name='massages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.chat'),
        ),
    ]
