pipeline {
    agent { docker { image 'python:3.7-alpine' } }
    triggers {
      githubPush()
  }

    stages {
        stage('Build') {
            steps {
                sh 'python --version'
            }

        }
        stage('setup'){
          steps{
            withEnv(["HOME=${env.WORKSPACE}"]){
            sh 'python -m pip install -r requirements.txt'
          }
          }
        }
         stage('Run Unit Tests') {
                steps {
              withEnv(["HOME=${env.WORKSPACE}"]) {
                sh 'python manage.py test'
                sh 'ls -l'

            }
          }
            }




    }

}