pipeline {
    agent { docker { image 'python:3.7.0' } }
    stages {
        stage('Install Application Dependencies') {
            sh '''
        source bin/activate
        pip install -r requirements.txt
        deactivate
       '''
        }
    }
}