pipeline {
    agent { docker { image 'python:3.7-alpine' } }
    triggers {
      githubPush()
  }

    stages {
        stage('Build') {
            steps {
                sh 'python --version'
            }

        }
        stage('setup'){
          steps{
            withEnv(["HOME=${env.WORKSPACE}"]){
            sh 'python -m pip install -r requirements.txt'
            sh 'pip install coverage '
          }
          }
        }
         stage('Run Unit Tests') {
                steps {
              withEnv(["HOME=${env.WORKSPACE}"]) {
                sh 'python -m coverage run manage.py test work'
            }
          }
            }
        stage('Send mail'){
           steps{
            step([$class: 'Mailer', notifyEveryUnstableBuild: true, recipients: 'dora4@ac.sce.ac.il', sendToIndividuals: true])
        }


    }

}